/****** VIEWLIST *****/

export const FETCH_LIST = "FETCH_LIST";
export const FETCH_LIST_INIT = "FETCH_LIST_INIT";
export const FETCH_LIST_SUCCESS = "FETCH_LIST_SUCCESS";
export const FETCH_LIST_FAILURE = "FETCH_LIST_FAILURE";

/***** DETAIL *****/

export const DETAIL_INIT = "DETAIL_INIT";
export const DETAIL_SELECTED = "DETAIL_SELECTED";
export const DETAIL_SELECT_NEXT = "DETAIL_SELECT_NEXT";
export const DETAIL_SELECT_PREVIOUS = "DETAIL_SELECT_PREVIOUS";
